// This file is auto-generated by @hey-api/openapi-ts

export const $Pet = {
    type: 'object',
    properties: {
        name: {
            type: 'string'
        },
        id: {
            type: 'number'
        }
    },
    required: ['name', 'id']
} as const;