// This file is auto-generated by @hey-api/openapi-ts

import type { CancelablePromise } from './core/CancelablePromise';
import { OpenAPI } from './core/OpenAPI';
import { request as __request } from './core/request';
import type { GetPetsData, GetPetsResponse } from './types.gen';

export class DefaultService {
    /**
     * @param data The data for the request.
     * @param data.limit
     * @param data.page
     * @returns unknown Returns a list of pets
     * @throws ApiError
     */
    public static getPets(data: GetPetsData = {}): CancelablePromise<GetPetsResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/pets',
            query: {
                limit: data.limit,
                page: data.page
            }
        });
    }
    
}